services:
  - type: web
    name: smart-class-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      sleep 15
      echo "📢 Migrando base de datos"
      python manage.py migrate --noinput
      echo "📢 Creando superusuario si no existe"
      python manage.py create_initial_data
    startCommand: gunicorn smart_class_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: smart_class_backend.settings
      - key: SECRET_KEY
        value: tu_clave_secreta
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        value: postgresql://smart_class_db2_user:dbpfMbOzf2CtGde9GEU5pmxpPpIaOeqR@dpg-d106jm63jp1c739lvogg-a.oregon-postgres.render.com:5432/smart_class_db2
