# Generated by Django 5.2.1 on 2025-05-24 21:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0002_studentprofile_first_name_studentprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['year', 'period_type', 'number'], 'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='period',
            name='number',
            field=models.IntegerField(default=1, help_text='Número del período (1-4 para bimestres, 1-3 para trimestres)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='period_type',
            field=models.CharField(choices=[('bimester', 'Bimestral'), ('trimester', 'Trimestral')], default='bimester', help_text='Tipo de período: bimestral o trimestral', max_length=10),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(help_text='Año o gestión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.group')),
                ('periods', models.ManyToManyField(blank=True, help_text='Períodos asignados a esta clase', related_name='classes', to='academic.period')),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_classes', to='users.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='users.teacherprofile')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'unique_together': {('subject', 'course', 'group', 'year', 'teacher')},
            },
        ),
        migrations.RemoveField(
            model_name='period',
            name='bimester',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Falta'), ('absent_with_excuse', 'Falta con Licencia')], default='present', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academic.period')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.studentprofile')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academic.class')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-date', 'student__first_name'],
                'unique_together': {('class_instance', 'student', 'period', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('level', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='academic.class')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='academic.period')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Participación',
                'verbose_name_plural': 'Participaciones',
                'ordering': ['-date', 'student__first_name'],
                'unique_together': {('class_instance', 'student', 'period', 'date')},
            },
        ),
    ]
