# Generated by Django 5.2.1 on 2025-05-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_period_options_alter_period_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('period_type', 'number', 'year')},
        ),
    ]
