# Generated by Django 5.2.1 on 2025-06-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_period_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('presente', 'Presente'), ('falta', 'Falta'), ('tardanza', 'Tardanza')], default='presente', max_length=20),
        ),
        migrations.AlterField(
            model_name='participation',
            name='level',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_type',
            field=models.CharField(choices=[('bimestre', 'Bimestral'), ('trimestre', 'Trimestral')], default='bimestre', help_text='Tipo de período: bimestral o trimestral', max_length=10),
        ),
    ]
