# Generated by Django 5.2.1 on 2025-06-03 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_actions', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('failed_actions', models.IntegerField(default=0)),
                ('most_common_action', models.CharField(blank=True, max_length=50)),
                ('most_active_user', models.CharField(blank=True, max_length=150)),
                ('login_count', models.IntegerField(default=0)),
                ('create_count', models.IntegerField(default=0)),
                ('update_count', models.IntegerField(default=0)),
                ('delete_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resumen de Auditoría',
                'verbose_name_plural': 'Resúmenes de Auditoría',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Intento de inicio de sesión fallido'), ('USER_CREATE', 'Creación de usuario'), ('USER_UPDATE', 'Actualización de usuario'), ('USER_DELETE', 'Eliminación de usuario'), ('USER_VIEW', 'Visualización de usuario'), ('TEACHER_PROFILE_CREATE', 'Creación de perfil de profesor'), ('TEACHER_PROFILE_UPDATE', 'Actualización de perfil de profesor'), ('STUDENT_PROFILE_CREATE', 'Creación de perfil de estudiante'), ('STUDENT_PROFILE_UPDATE', 'Actualización de perfil de estudiante'), ('PERIOD_CREATE', 'Creación de período'), ('PERIOD_UPDATE', 'Actualización de período'), ('PERIOD_DELETE', 'Eliminación de período'), ('PERIOD_VIEW', 'Visualización de período'), ('SUBJECT_CREATE', 'Creación de materia'), ('SUBJECT_UPDATE', 'Actualización de materia'), ('SUBJECT_DELETE', 'Eliminación de materia'), ('SUBJECT_VIEW', 'Visualización de materia'), ('COURSE_CREATE', 'Creación de curso'), ('COURSE_UPDATE', 'Actualización de curso'), ('COURSE_DELETE', 'Eliminación de curso'), ('COURSE_VIEW', 'Visualización de curso'), ('GROUP_CREATE', 'Creación de grupo'), ('GROUP_UPDATE', 'Actualización de grupo'), ('GROUP_DELETE', 'Eliminación de grupo'), ('GROUP_VIEW', 'Visualización de grupo'), ('CLASS_CREATE', 'Creación de clase'), ('CLASS_UPDATE', 'Actualización de clase'), ('CLASS_DELETE', 'Eliminación de clase'), ('CLASS_VIEW', 'Visualización de clase'), ('CLASS_ADD_STUDENT', 'Añadir estudiante a clase'), ('CLASS_REMOVE_STUDENT', 'Remover estudiante de clase'), ('CLASS_ADD_PERIOD', 'Añadir período a clase'), ('CLASS_REMOVE_PERIOD', 'Remover período de clase'), ('ATTENDANCE_CREATE', 'Registro de asistencia'), ('ATTENDANCE_UPDATE', 'Actualización de asistencia'), ('ATTENDANCE_DELETE', 'Eliminación de asistencia'), ('ATTENDANCE_BULK_CREATE', 'Registro masivo de asistencia'), ('ATTENDANCE_VIEW', 'Visualización de asistencia'), ('ATTENDANCE_STATS', 'Consulta de estadísticas de asistencia'), ('PARTICIPATION_CREATE', 'Registro de participación'), ('PARTICIPATION_UPDATE', 'Actualización de participación'), ('PARTICIPATION_DELETE', 'Eliminación de participación'), ('PARTICIPATION_BULK_CREATE', 'Registro masivo de participación'), ('PARTICIPATION_VIEW', 'Visualización de participación'), ('PARTICIPATION_STATS', 'Consulta de estadísticas de participación'), ('GRADE_CREATE', 'Registro de nota'), ('GRADE_UPDATE', 'Actualización de nota'), ('GRADE_DELETE', 'Eliminación de nota'), ('GRADE_BULK_CREATE', 'Registro masivo de notas'), ('GRADE_VIEW', 'Visualización de notas'), ('GRADE_STATS', 'Consulta de estadísticas de notas'), ('FINAL_GRADE_RECALCULATE', 'Recálculo de notas finales'), ('PREDICTION_CREATE', 'Creación de predicción'), ('PREDICTION_UPDATE', 'Actualización de predicción'), ('PREDICTION_VIEW', 'Visualización de predicción'), ('PREDICTION_RETRAIN', 'Reentrenamiento de modelo'), ('PREDICTION_BULK_UPDATE', 'Actualización masiva de predicciones'), ('PREDICTION_RETROSPECTIVE', 'Generación de predicciones retrospectivas'), ('SYSTEM_ERROR', 'Error del sistema'), ('API_ACCESS', 'Acceso a API'), ('UNAUTHORIZED_ACCESS', 'Acceso no autorizado')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'), models.Index(fields=['ip_address', '-timestamp'], name='audit_audit_ip_addr_ed092b_idx'), models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx')],
            },
        ),
    ]
